FROM maven:3.8.4-openjdk-11 AS builder
WORKDIR /app/JtProject
COPY . /app
RUN mvn clean install

FROM openjdk:11-jdk
WORKDIR /app
COPY --from=builder /app/JtProject/target/JtSpringProject-0.0.1-SNAPSHOT.jar /app